title: My super page
author: Yevhen Tkachenko
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It is none professional git web site created by Yevhen Tkachenko.
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  t-jay-777

show_excerpts: true # set to false to remove excerpts on the homepage
